package com.linken.ad.data;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "AD_DOWNLOAD_FILE".
 */
@Entity
public class AdDownloadFile {

    @Id(autoincrement = true)
    private Long id;
    private String packageName;
    private String localFile;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 677540028)
    public AdDownloadFile() {
    }

    public AdDownloadFile(Long id) {
        this.id = id;
    }

    @Generated(hash = 152538431)
    public AdDownloadFile(Long id, String packageName, String localFile) {
        this.id = id;
        this.packageName = packageName;
        this.localFile = localFile;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getLocalFile() {
        return localFile;
    }

    public void setLocalFile(String localFile) {
        this.localFile = localFile;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
