package com.linken.ad.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.linken.ad.data.RewardCard;
import com.linken.ad.data.AdDownloadFile;
import com.linken.ad.data.AdvertisementCard;

import com.linken.ad.data.RewardCardDao;
import com.linken.ad.data.AdDownloadFileDao;
import com.linken.ad.data.AdvertisementCardDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rewardCardDaoConfig;
    private final DaoConfig adDownloadFileDaoConfig;
    private final DaoConfig advertisementCardDaoConfig;

    private final RewardCardDao rewardCardDao;
    private final AdDownloadFileDao adDownloadFileDao;
    private final AdvertisementCardDao advertisementCardDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rewardCardDaoConfig = daoConfigMap.get(RewardCardDao.class).clone();
        rewardCardDaoConfig.initIdentityScope(type);

        adDownloadFileDaoConfig = daoConfigMap.get(AdDownloadFileDao.class).clone();
        adDownloadFileDaoConfig.initIdentityScope(type);

        advertisementCardDaoConfig = daoConfigMap.get(AdvertisementCardDao.class).clone();
        advertisementCardDaoConfig.initIdentityScope(type);

        rewardCardDao = new RewardCardDao(rewardCardDaoConfig, this);
        adDownloadFileDao = new AdDownloadFileDao(adDownloadFileDaoConfig, this);
        advertisementCardDao = new AdvertisementCardDao(advertisementCardDaoConfig, this);

        registerDao(RewardCard.class, rewardCardDao);
        registerDao(AdDownloadFile.class, adDownloadFileDao);
        registerDao(AdvertisementCard.class, advertisementCardDao);
    }
    
    public void clear() {
        rewardCardDaoConfig.clearIdentityScope();
        adDownloadFileDaoConfig.clearIdentityScope();
        advertisementCardDaoConfig.clearIdentityScope();
    }

    public RewardCardDao getRewardCardDao() {
        return rewardCardDao;
    }

    public AdDownloadFileDao getAdDownloadFileDao() {
        return adDownloadFileDao;
    }

    public AdvertisementCardDao getAdvertisementCardDao() {
        return advertisementCardDao;
    }

}
