package com.linken.ad.data;

import com.linken.newssdk.data.card.base.Card;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;

import java.io.Serializable;

import org.greenrobot.greendao.annotation.Generated;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ADVERTISEMENT_CARD".
 */
@Entity
public class RewardCard implements Serializable {

    private static final long serialVersionUID = -8112172681584451578L;
    @Id(autoincrement = true)
    private Long id;
    private String cardId;
    private String type;
    @Generated(hash = 1938472551)
    public RewardCard(Long id, String cardId, String type) {
        this.id = id;
        this.cardId = cardId;
        this.type = type;
    }
    @Generated(hash = 1907221929)
    public RewardCard() {
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getCardId() {
        return this.cardId;
    }
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }
    public String getType() {
        return this.type;
    }
    public void setType(String type) {
        this.type = type;
    }

}
