package com.linken.ad.data;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ADVERTISEMENT_CARD".
 */
@Entity
public class RewardCard implements Serializable {

    private static final long serialVersionUID = 9140417067992669524L;
    @Id(autoincrement = true)
    private Long id;
    private String cardId;
    private String type;

    public RewardCard(String cardId, String type) {
        this.cardId = cardId;
        this.type = type;
    }

    @Generated(hash = 1333866245)
    public RewardCard(Long id, String cardId, String type) {
        this.id = id;
        this.cardId = cardId;
        this.type = type;
    }

    @Generated(hash = 1907221929)
    public RewardCard() {
    }

    public String getCardId() {
        return cardId;
    }

    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
